#!/bin/bash

# MySQL Setup Script for NutriTrack
# This script helps fix MySQL authentication issues

echo "=== MySQL Setup for NutriTrack ==="
echo ""
echo "Option 1: Create a new MySQL user (Recommended)"
echo "Run these commands in MySQL:"
echo ""
echo "sudo mysql"
echo ""
echo "Then in MySQL, run:"
echo "CREATE USER IF NOT EXISTS 'sssmvc'@'localhost' IDENTIFIED BY 'sssmvc123';"
echo "CREATE DATABASE IF NOT EXISTS sssmvc;"
echo "GRANT ALL PRIVILEGES ON sssmvc.* TO 'sssmvc'@'localhost';"
echo "FLUSH PRIVILEGES;"
echo "EXIT;"
echo ""
echo "Option 2: Enable password authentication for root"
echo "Run: sudo mysql"
echo "Then: ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'your_password';"
echo "FLUSH PRIVILEGES;"
echo "EXIT;"
echo ""
echo "After setting up MySQL, update your .env file:"
echo "DB_CONNECTION=mysql"
echo "DB_HOST=127.0.0.1"
echo "DB_PORT=3306"
echo "DB_DATABASE=sssmvc"
echo "DB_USERNAME=sssmvc"
echo "DB_PASSWORD=sssmvc123"
echo ""
echo "Then run: php artisan migrate"

